### ISSUE TITLE
Can't start or build

### ISSUE THREAD

**Issue by lePioo** [kevoj/electron-react-ant-boilerplate#1]
I cloned the repo, npm install, then when I try npm run start or npm run build it get stucks at
`
> electron-react-ant-boilerplate@1.0.4 build C:\Users\me\ElectronProjects\electron-react-ant-boilerplate
> node -r @babel/register & webpack --config webpack.prod.config.babel.js
>
`

**Comment by kevoj** [comment]
Hi, I do not see any error, you could send me a screen of the error I see that you are from windows, make sure you have an updated version of Node

**Comment by lePioo** [comment]
https://image.noelshack.com/fichiers/2019/15/7/1555255722-npm-start-issue.png

**Comment by kevoj** [comment]
Great, there is indeed a bug in Windows, I will fix it in the course of the day, I thank you for detecting it and informing me!

**Comment by kevoj** [comment]
Windows compatibility has been integrated :)
