### ISSUE TITLE
Cannot find module 'fs'

### ISSUE THREAD

**Issue by niravbhimani53** [kevoj/electron-react-ant-boilerplate#2]
Hi,
I am trying to import inside the layouts/App.js.

```
const { ipcRenderer } = require('electron')
const remote = require('electron').remote
```

On `npm start` I am encountering an error,
```

index.js:1 Uncaught Error: Cannot find module 'fs'            index.js:1
    at webpackMissingModule (index.js:1)
    at Object.<anonymous> (index.js:1)
    at Object../node_modules/electron/index.js (index.js:18)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.<anonymous> (App.js:10)
    at Object../src/layouts/App.js (App.js:19)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.<anonymous> (Home.js:6)
```

```
./node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in
'directory/electron-react-ant-boilerplate/node_modules/electron'
```

To solve this I tried to add 
```
base: {
  node: {
    fs: 'empty'
  },
  module: {
     ...
  }
}
```
on line 101 inside const config in file `webpack.config.babel.js`, then I got new error

```
Uncaught TypeError: fs.existsSync is not a function
    at getElectronPath (index.js:7)
    at Object.<anonymous> (index.js:18)
    at Object../node_modules/electron/index.js (index.js:18)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.<anonymous> (App.js:10)
    at Object../src/layouts/App.js (App.js:19)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object.<anonymous> (Home.js:6)
```

Is there any solution?

**Comment by bytesleo** [comment]
Hi, you basically need to install "fs" as a module:

```bash
npm install fs --save
```

And well, you may also require electron as production dependency

```bash
npm install electron --save
```

**Comment by niravbhimani53** [comment]
Hi,
It doesn't solve the problem. Still getting the same error.
Command `npm install fs --save` is installing some security package which contains readme file only.

**Comment by bytesleo** [comment]
You could attach a screenshot of the console pls

Do not forget to undo these changes:


```javsacript
base: {
  node: {
    fs: 'empty'
  },
  module: {
     ...
  }
}
```

**Comment by bytesleo** [comment]
Man, u can try with this code:
```javascript
const electron = window.require("electron")

```

**Comment by niravbhimani53** [comment]
<img width="549" alt="Screen Shot 2019-05-05 at 10 53 40 am" src="https://user-images.githubusercontent.com/12537912/57186518-10a0f300-6f24-11e9-8bed-d680b4e67735.png">

**Comment by bytesleo** [comment]
Well, I think I have it, I just tried it:

1. `webpack.config.babel.js`

```javascript
base: {
  node: {
    fs: 'empty'
  },
  module: {
     ...
  }
}
```

2. ` layouts/App.js`

```javascript
const { ipcRenderer } = window.require("electron");
const remote = window.require("electron").remote;
```

**Comment by niravbhimani53** [comment]
> Well, I think I have it, I just tried it:
> 
> 1. `webpack.config.babel.js`
> 
> ```js
> base: {
>   node: {
>     fs: 'empty'
>   },
>   module: {
>      ...
>   }
> }
> ```
> 
> 1. ` layouts/App.js`
> 
> ```js
> const { ipcRenderer } = window.require("electron");
> const remote = window.require("electron").remote;
> ```

**Comment by niravbhimani53** [comment]
Sorry, are you getting the same errors?

**Comment by bytesleo** [comment]
I made your same mistakes happen, then I solved them as I indicated in my previous comment!

**Comment by niravbhimani53** [comment]
Thanks for help

**Comment by bytesleo** [comment]
Did it work ?, Anything you tell me and with pleasure I help you ;)

**Comment by niravbhimani53** [comment]
Yup, it worked. Cheers
