### ISSUE TITLE
Importing style from .scss

### ISSUE THREAD

**Issue by niravbhimani53** [kevoj/electron-react-ant-boilerplate#3]
Hi,
I have noticed that CSS from the .scss file are imported into styles and then styles.app or styles.helloWorld is used. Is there any particular reason for that?

Isnt `importing "myStylesheet.scss"` enough at the start?

Cheers

**Comment by bytesleo** [comment]
Hi, there are several ways to import style files in React, as it is by default by modules, this guarantees that I can use the same class names in many modules and will not affect in any way another style, the dynamic was to use the main name of the module and place it in the main style, now, you are free to use any of the following ways to integrate the styles:

**1. Modules**
```javascript
import styles from "./HelloWorld.scss";

// JSX
<div className={styles.helloWorld}>Hello World!</div>
```

**2. Global**
```javascript
import "./HelloWorld.global.scss";

// JSX
<div className="hello-world">Hello World!</div>
```

**3. Inline styling**
```javascript
const helloWorld= {
  margin: '40px',
  border: '5px solid pink'
};

// JSX
 <div style={helloWorld}>
    hello
 </div>
```

**4. Styled-component**
```bash
npm install styled-components --save
```
```javascript
import styled from 'styled-components';

const HelloWorld= styled.div`
  margin: 40px;
  border: 5px outset pink;
  &:hover {
   background-color: yellow;
 }
`;

// JSX
 <HelloWorld>
    hello
 </HelloWorld>
```

**Comment by niravbhimani53** [comment]
There is an issue with when using SCSS as global as you mentioned in point 2.

Steps to reproduce
HelloWorld.js
```
import "./Home.scss";

<div>
     <span  className="test_1">
        Test 1
     </span>
    <br />
    <span className="test_2">
        Test 2
    </span>
</div>
```

HelloWorld.scss
```
.test_1 {
  font-size: 2rem;
}

.test_2 {
  font-size: 3rem;
}
```

Style is not being rendered when using `npm start`. Default CSS from body is used for rendering above div tag. While inspecting in the Inspect tab, SCSS is converted into
<img width="355" alt="Screen Shot 2019-05-05 at 12 23 20 pm" src="https://user-images.githubusercontent.com/12537912/57187364-a6427f80-6f30-11e9-88cd-c49473bedd33.png">

**Comment by bytesleo** [comment]
Remember to add ".global.scss", since it will be used globally, in your case:
```bash
HelloWorld.global.scss
```
