### ISSUE TITLE
Problem with antd dark theme

### ISSUE THREAD

**Issue by DonsWayo** [kevoj/electron-react-ant-boilerplate#5]
Error: Cannot find module './src/ant-design/dark-theme' after install the theme via npm and put in the less loader, any idea why?

const lessLoader = AntdScssThemePlugin.themify({
  loader: "less-loader",
  options: {
    modifyVars: darkTheme,
    sourceMap: isDev,
    javascriptEnabled: true
  }
});

**Comment by bytesleo** [comment]
Hi, the right way:
1.  Copy vars: https://github.com/ant-design/ant-design-dark-theme/blob/master/index.ts
2.  Paste in https://github.com/kevoj/electron-react-ant-boilerplate/blob/develop/src/themes/Ant.vars.scss
3. Replace "@" with "$"
4. Enjoy :)

Note: It is precisely one of the strengths of this stack, to have the possibility to write in Antd SASS directly from the project

**Comment by bytesleo** [comment]
'@highlight-color': red[7],  -> #cf1322
'@warning-color': gold[9], -> #874d00

More:
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

**Comment by DonsWayo** [comment]
Hi thanks for the info, I will try!, I have other issue, may be I need to open other but can be close with these. When I add a library with css components like react-snippers or atlassian packages, I have errors like 'module not found' maybe webpack issue?. I make a simple demo on stackblitz that the same code not work on the boilerpalete

https://stackblitz.com/edit/react-px7lnw

**Comment by DonsWayo** [comment]
I solved added the @import "~storm-react-diagrams/src/sass/main";
to te main app scss
