### ISSUE TITLE
Unable to use  Atlaskit (CSS library)

### ISSUE THREAD

**Issue by DonsWayo** [kevoj/electron-react-ant-boilerplate#6]
I cannot compile with Atlaskit components, May be because are written in CSS, some webpack issue?. I attached a demo on simple create react app that not work with the boilerplate because cannot find the modules.

https://stackblitz.com/edit/react-px7lnw

**Comment by bytesleo** [comment]
hi, r u sure you passed the correct example?

**Comment by bytesleo** [comment]
If u want to talk more deeply write me here bro https://twitter.com/k3voj
